#!/bin/sh

# sudo not required for some system commands
for command in poweroff reboot; do
	alias $command="doas $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias bc="bc -ql"
alias rsync="rsync -vrPlu"
alias mkdir="mkdir -pv"
alias sha="shasum -a 256" 
# Colorize commands when possible.
alias ls="ls -xhA --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto" 
alias ccat="highlight --out-format=ansi"
alias ip="ip -color=auto"
alias g="git"
alias startplasma="XDG_SESSION_TYPE=wayland dbus-run-session startplasma-wayland"
