#!/bin/sh

# xinitrc runs automatically when you run startx.

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"

dwmblocks &

exec dbus-launch --exit-with-session dwm
