#!/bin/sh

xrandr -s 1920x1080
#setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

# autostart="xcompmgr" # dunst"

# for program in $autostart; do
# 	pidof -sx "$program" || "$program" &
# done >/dev/null 2>&1

# picom &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"