# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

export VISUAL=nano
export EDITOR="$VISUAL"
export GTK_THEME=Adwaita:dark

alias myip='curl ipinfo.io/ip'
alias untar='tar -zxvf'
alias sha='shasum -a 256'
alias ls='ls -xhA --color=auto --group-directories-first'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -rv'
alias mkdir='mkdir -pv'
alias wifi='nmcli device wifi'

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

unset rc
