#!/bin/sh

xsetroot -cursor_name left_ptr &
xrdb ~/.Xresources &
#xrandr -s 1920x1080
polybar &
feh --no-fehbg --bg-fill '/home/bmeyer/bg.png' &
sxhkd &
/usr/libexec/xfce-polkit &
fastfetch &

bspc monitor -d 1 2 3 4

bspc config focused_border_color "#607a9f"
bspc config normal_border_color "#393f46"
bspc config border_radius 4
bspc config border_width 2
bspc config window_gap 8
bspc config split_ratio 0.5
bspc config focus_follows_pointer true
bspc config automatic_scheme spiral
